title: A Wee Foray into GitHub Pages
author: Crumeniferus
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A short blog with one, maybe two entries, to get the hang of 
  GitHub Pages in a repository that holds nothign of personal value.

# social links
twitter_username: your-twitter-handle
github_username:  crumeniferus

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
